spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pizzeria?useSSL=false&allowPublicKeyRetrieval=true
    username: pizzaiolo
    password: PizzaioloDePizzaHut
  jpa:
    hibernate:
      naming:
        physical-strategy: 'org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl'